[project]
name = "django-dev"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.4",
    "google-adk[a2a]>=1.8.0",
    "mysqlclient>=2.2.7",
]
